services:
  - type: web
    name: lyric-mistakes
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: MAPBOX_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
